### ISSUE TITLE
feat: fisheye accepts abstract focus point instead of visual focus point

### ISSUE THREAD

**Issue by pearmini** [antvis/coord#39]
Currently fisheye accepts visual focus point, which means it must be specified after cartesian coordinate. 

```js
const coord = new Coordinate({
  width: 300,
  height: 150,
});
coord.transform('cartesian');
coord.transform('fisheye', 150, 75, 2, 2);
coord.map([0.4, 0.2]); // [85.71428571428571, 13.63636363636364]
```

This is inconsistent with other coordinate transformations, such as polar.

```js
const coord = new Coordinate();
coord.transform('polar', -Math.PI / 2, (Math.PI * 3) / 2, 0, 1);
coord.transform('cartesian');
```
A better implementation is enabling fisheye to accept abstract focus point(normalized point).

```js
const coord = new Coordinate({
  width: 300,
  height: 150,
});

// The first way to declare.
coord.transform('fisheye', 0.5, 0.5, 2, 2); // Abstract value by default.
coord.transform('cartesian');

// The second way to declare.
coord.transform('fisheye', 300, 150, 2, 2, true);  // Flag to treat it as visual value.
coord.transform('cartesian');

// Result the same.
coord.map([0.4, 0.2]); // [85.71428571428571, 13.63636363636364]
```
The key to achieving this goal is to pass [0, 1] for the range of fisheyeTransform, and normalize focusX before point transformations. - [source](https://github.com/antvis/coord/blob/master/src/transforms/fisheye.ts#L83)

```js
// Before
const fx = fisheyeTransform(vx, focusX, distortionX, x, x + width); // focusX is visual value.

// After
const normalizedFocusX = normlize(focusX, isVisual);
const fx = fisheyeTransform(vx, normalizedFocusX, distortionX, 0, 1); 
```

**Todo List**
- [ ] fisheye - code, test, docs
- [ ] fisheyeX - code, test, docs
- [ ] fisheyeY - code, test, docs
